version: "3.8"
services:
    frontend:
        build:
            context: ./frontend # Path to your React app
        ports:
            - "5173:5173"
        depends_on:
            - backend
        environment:
            - VITE_API_URL=http://backend:3000 # The backend service name

    backend:
        build:
            context: ./backend # Path to your Express app
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
